"use client";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import MapArea from "./MapArea";
import styles from "./Home.module.css";

export default function Home() {
  const [coordinates, setCoordinates] = useState({
    lat: 2.996576908645812,
    lng: 101.59493478782426,
  });
  console.log(process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center w-screen, h-screen bg-gray-100">
        <h1 className="m-4 justify-center">
          GMap's and GAutocomplete app built using NextJS and{" "}
          <a
            className="font-bold underline"
            href="https://react-google-maps-api-docs.netlify.app/"
          >
            @react-google-maps/api
          </a>
          . Create .env.local file and add your google api key to get started.
        </h1>
        <MapArea
          className="mb-4"
          setCoordinates={setCoordinates}
          coordinates={coordinates}
        ></MapArea>
        {/* <GooglePlacesAutocomplete
          className="w-full rounded border px-2"
          apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}
        /> */}
        {/* <Autocomplete
          className="rounded border my-20 px-2"
          apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}
          onPlaceSelected={(place) => {
            console.log(place);
          }}
        />*/}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Waqas Khalid Obeidy{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
